[model]
NODES_X = 50
NODES_Y = 50
TOROIDAL = true

[agents]
AGENT = 0
WALKER = 3
GRAZER = 5
LOOPYGRAZER = 1
SLOWBOY = 10
FOOD = 5
FLOWER = 10
FADE_THRESHOLD = 10

[display]
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 800
FPS = 60 # 0 means uncapped FPS

[colors]
BACKGROUND_COLOR = [0, 0, 0]
