[model]
NODES_X = 50
NODES_Y = 50
TOROIDAL = true

[agents]
AGENT = 0
WALKER = 0
GRAZER = 0
LOOPYGRAZER = 5
SLOWBOY = 0
FOOD = 0
FLOWER = 5
FADE_THRESHOLD = 10

[display]
DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 800
FPS = 60

[colors]
BACKGROUND_COLOR = [0, 0, 0]
